sudo: required

services:
  - docker
node_js:
  - '6'
script:
  - echo 'TODO: add integration tests'

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - dockyard build image --repo=npmjs --name=npm-docker-couchdb
